In [1]:
#Q.1
#(a)

import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 6 3 2 1]


In [4]:
#(b)

array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flat1 = array1.flatten()
print(flat1)

[1 2 3 2 4 5 1 2 3]


In [5]:
#(c)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(np.array_equal(arr1, arr2))  
print((arr1 == arr2).all())

True
True


In [7]:
#(d)
#(i)

from collections import Counter
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
freq = Counter(x)
most_common_val, count = freq.most_common(1)[0]
indices = np.where(x == most_common_val)[0]
print("Most frequent value:", most_common_val)
print("Indices of most frequent value:", indices)

#(ii)
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
freq_y = Counter(y)
most_common_val_y, count_y = freq_y.most_common(1)[0]
indices_y = np.where(y == most_common_val_y)[0]
print("Most frequent value:", most_common_val_y)
print("Indices of most frequent value:", indices_y)

Most frequent value: 1
Indices of most frequent value: [0 5 7 8 9]
Most frequent value: 1
Indices of most frequent value: [0 1 2]


In [8]:
#(e)
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

#(i)
total_sum = gfg.sum()
print("Sum of all elements:", total_sum)

#(ii)
row_sum = gfg.sum(axis=1)
print("Sum of all elements row-wise:\n", row_sum)

#(iii)
col_sum = gfg.sum(axis=0)
print("Sum of all elements column-wise:\n", col_sum)

Sum of all elements: 45
Sum of all elements row-wise:
 [[14]
 [16]
 [15]]
Sum of all elements column-wise:
 [[20  9 16]]


In [9]:
#(f)
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])

#(i)
diagonal_sum = np.trace(n_array)
print("Sum of diagonal elements:", diagonal_sum)

#(ii)
eigenvalues, eigenvectors = np.linalg.eig(n_array)
print("Eigenvalues of the matrix:", eigenvalues)

#(iii)
print("Eigenvectors of the matrix:\n", eigenvectors)

#(iv)
try:
    inverse_matrix = np.linalg.inv(n_array)
    print("Inverse of the matrix:\n", inverse_matrix)
except np.linalg.LinAlgError:
    print("Matrix is not invertible.")

#(iv)
determinant = np.linalg.det(n_array)
print("Determinant of the matrix:", determinant)

Sum of diagonal elements: 176
Eigenvalues of the matrix: [98.16835147 28.097044   49.73460452]
Eigenvectors of the matrix:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of the matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of the matrix: 137180.0000000001


In [10]:
#(g)

#(i)
p_i = np.array([[1, 2], [2, 3]])
q_i = np.array([[4, 5], [6, 7]])
result_multiplication_i = np.dot(p_i, q_i)
print("Matrix Multiplication of p and q (i):\n", result_multiplication_i)
covariance_matrix_i = np.cov(p_i.flatten(), q_i.flatten())
print("Covariance between matrices p and q (i):\n", covariance_matrix_i)

#(ii)
p_ii = np.array([[1, 2], [2, 3], [4, 5]])
q_ii = np.array([[4, 5, 1], [6, 7, 2]])
result_multiplication_ii = np.dot(p_ii, q_ii)
print("Matrix Multiplication of p and q (ii):\n", result_multiplication_ii)
covariance_matrix_ii = np.cov(p_ii.flatten(), q_ii.flatten())
print("Covariance between matrices p and q (ii):\n", covariance_matrix_ii)


Matrix Multiplication of p and q (i):
 [[16 19]
 [26 31]]
Covariance between matrices p and q (i):
 [[0.66666667 1.        ]
 [1.         1.66666667]]
Matrix Multiplication of p and q (ii):
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance between matrices p and q (ii):
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [11]:
#(h)
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# Inner product
inner_product = np.dot(x, y.T)
print("Inner Product (Dot Product) of x and y:\n", inner_product)

# Outer product
outer_product_1 = np.outer(x[0], y[0])  # Outer product of first rows
outer_product_2 = np.outer(x[1], y[1])  # Outer product of second rows
print("Outer Product (Row 1 of x and Row 1 of y):\n", outer_product_1)
print("Outer Product (Row 2 of x and Row 2 of y):\n", outer_product_2)

# Cartesian product 
x_mesh, y_mesh = np.meshgrid(x.flatten(), y.flatten())
cartesian_product = np.vstack([x_mesh.flatten(), y_mesh.flatten()]).T
print("Cartesian Product of x and y:\n", cartesian_product)


Inner Product (Dot Product) of x and y:
 [[17 52]
 [13 62]]
Outer Product (Row 1 of x and Row 1 of y):
 [[ 2 10  0]
 [ 3 15  0]
 [ 4 20  0]]
Outer Product (Row 2 of x and Row 2 of y):
 [[15 30  9]
 [10 20  6]
 [45 90 27]]
Cartesian Product of x and y:
 [[ 2  1]
 [ 3  1]
 [ 4  1]
 [ 3  1]
 [ 2  1]
 [ 9  1]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2  0]
 [ 3  0]
 [ 4  0]
 [ 3  0]
 [ 2  0]
 [ 9  0]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2 10]
 [ 3 10]
 [ 4 10]
 [ 3 10]
 [ 2 10]
 [ 9 10]
 [ 2  3]
 [ 3  3]
 [ 4  3]
 [ 3  3]
 [ 2  3]
 [ 9  3]]


In [12]:
#Q.2

#(a)
array = np.array([[1, -2, 3], [-4, 5, -6]])

#(i)
abs_value = np.abs(array)
print("Element-wise absolute value:\n", abs_value)

#(ii)
flattened_array = array.flatten()
percentiles_flattened = np.percentile(flattened_array, [25, 50, 75])
print("Percentiles (25th, 50th, 75th) of flattened array:\n", percentiles_flattened)

percentiles_column = np.percentile(array, [25, 50, 75], axis=0)
print("Percentiles (25th, 50th, 75th) for each column:\n", percentiles_column)

percentiles_row = np.percentile(array, [25, 50, 75], axis=1)
print("Percentiles (25th, 50th, 75th) for each row:\n", percentiles_row)

#(iii)
mean_flattened = np.mean(flattened_array)
median_flattened = np.median(flattened_array)
std_flattened = np.std(flattened_array)

print("Mean of flattened array:", mean_flattened)
print("Median of flattened array:", median_flattened)
print("Standard Deviation of flattened array:", std_flattened)

mean_column = np.mean(array, axis=0)
median_column = np.median(array, axis=0)
std_column = np.std(array, axis=0)

print("Mean for each column:\n", mean_column)
print("Median for each column:\n", median_column)
print("Standard Deviation for each column:\n", std_column)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

print("Mean for each row:\n", mean_row)
print("Median for each row:\n", median_row)
print("Standard Deviation for each row:\n", std_row)

Element-wise absolute value:
 [[1 2 3]
 [4 5 6]]
Percentiles (25th, 50th, 75th) of flattened array:
 [-3.5 -0.5  2.5]
Percentiles (25th, 50th, 75th) for each column:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles (25th, 50th, 75th) for each row:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean of flattened array: -0.5
Median of flattened array: -0.5
Standard Deviation of flattened array: 3.8622100754188224
Mean for each column:
 [-1.5  1.5 -1.5]
Median for each column:
 [-1.5  1.5 -1.5]
Standard Deviation for each column:
 [2.5 3.5 4.5]
Mean for each row:
 [ 0.66666667 -1.66666667]
Median for each row:
 [ 1. -4.]
Standard Deviation for each row:
 [2.05480467 4.78423336]


In [17]:
#(b)
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

#(ii)
floor_values = np.floor(a)
ceil_values = np.ceil(a)
trunc_values = np.trunc(a)

print("Floor values:\n", floor_values)
print("Ceiling values:\n", ceil_values)
print("Truncated values:\n", trunc_values)

rounded_values = np.round(a)
print("Rounded values:\n", rounded_values)

Floor values:
 [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values:
 [-1. -1. -0.  1.  2.  2.  3.]
Truncated values:
 [-1. -1. -0.  0.  1.  1.  3.]
Rounded values:
 [-2. -2. -0.  0.  2.  2.  3.]


In [18]:
#Q.3

#(a)
array_1 = np.array([10, 52, 62, 16, 16, 54, 453])

#(i)
sorted_array = np.sort(array_1)
print("Sorted array:", sorted_array)

#(ii)
indices_sorted = np.argsort(array_1)
print("Indices of sorted array:", indices_sorted)

#(iii)
smallest_4 = sorted_array[:4]
print("4 smallest elements:", smallest_4)

#(iv)
largest_5 = sorted_array[-5:]
print("5 largest elements:", largest_5)


#(b)
array_2 = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

#(i)
integer_elements = array_2[array_2 == np.floor(array_2)]
print("Integer elements only:", integer_elements)

#(ii)
float_elements = array_2[array_2 != np.floor(array_2)]
print("Float elements only:", float_elements)

Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]
Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


In [ ]:
#Q.4
#(a)
from PIL import Image
import numpy as np

def img_to_array(path, save_path):
    # Open the image file
    img = Image.open(path)
    
    # Check if the image is grayscale (mode 'L') or RGB (mode 'RGB')
    if img.mode == 'RGB':
        # Convert to NumPy array for RGB images
        img_array = np.array(img)
        print("Image is in RGB mode.")
    elif img.mode == 'L':
        # Convert to NumPy array for grayscale images
        img_array = np.array(img)
        print("Image is in Grayscale mode.")
    else:
        raise ValueError("Unsupported image mode: {}".format(img.mode))
    
    # Save the array as a text file
    np.savetxt(save_path, img_array.reshape(-1, img_array.shape[-1]) if img.mode == 'RGB' else img_array, fmt='%d')
    print(f"Image saved as a text file at {save_path}")

# Example usage:
# Path to the image you want to process
image_path = 'path_to_your_image.jpg'
# Path to save the output text file
save_text_path = 'image_array.txt'

img_to_array(image_path, save_text_path)


In [ ]:
#(b)
import numpy as np
import matplotlib.pyplot as plt

def load_image_from_txt(file_path, is_rgb=True):
    # Load the image array from the text file
    img_array = np.loadtxt(file_path, dtype=int)
    
    # Check if the image is RGB or Grayscale and reshape accordingly
    if is_rgb:
        # Reshape for RGB images (3 color channels)
        img_array = img_array.reshape((-1, 3))
        img_array = img_array.reshape((int(np.sqrt(img_array.shape[0])), -1, 3))  # Adjust this based on your image's original dimensions
    else:
        # Reshape for Grayscale images (2D)
        img_array = img_array.reshape(int(np.sqrt(img_array.shape[0])), -1)
    
    # Display the image
    plt.imshow(img_array)
    plt.axis('off')  # Turn off axis
    plt.show()

# Example usage
# Load the saved image text file and display it
load_image_from_txt('image_array.txt', is_rgb=True)
